import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Container } from '@/components/shared/container';
import { ThemeProvider } from '@/components/shared/theme-provider';

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'Todo App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider>
					<Container>{children}</Container>
				</ThemeProvider>
			</body>
		</html>
	);
}
